export const SECTION_GROUPS = [
  { id: 'atGlance', label: 'Wardrobe at a glance' },
  { id: 'styleHabits', label: 'Style & wearing habits' },
  { id: 'value', label: 'Value & sustainability' },
  { id: 'financial', label: 'Financial overview' },
];

export const INSIGHT_MODULES = [
  {
    id: 'overviewCards',
    title: 'Wardrobe snapshot',
    description: 'Quick view of totals and sustainability score.',
    section: 'atGlance',
    type: 'cards',
    span: 'lg:col-span-12',
  },
  {
    id: 'categoryBreakdown',
    title: 'Category mix',
    description: 'See how your wardrobe splits across categories.',
    section: 'atGlance',
    type: 'chart',
  },
  {
    id: 'colorPalette',
    title: 'Signature palette',
    description: 'Your most common wardrobe colors.',
    section: 'atGlance',
    type: 'palette',
  },
  {
    id: 'brandDistribution',
    title: 'Brands you love',
    description: 'Top brands in your closet.',
    section: 'atGlance',
    type: 'chart',
  },
  {
    id: 'fabricFocus',
    title: 'Fabric focus',
    description: 'Breakdown of materials in your closet.',
    section: 'atGlance',
    type: 'chart',
  },
  {
    id: 'newestAdditions',
    title: 'Newest additions',
    description: 'Fresh pieces you recently added.',
    section: 'atGlance',
    type: 'list',
  },
  {
    id: 'topGoToItems',
    title: 'Your go-to items',
    description: 'Most worn clothes and outfits.',
    section: 'styleHabits',
    type: 'list',
    span: 'lg:col-span-6 xl:col-span-4',
  },
  {
    id: 'wearTrend',
    title: 'Wear frequency',
    description: 'Monthly wear trend over time.',
    section: 'styleHabits',
    type: 'chart',
  },
  {
    id: 'forgottenFavorites',
    title: 'Forgotten favourites',
    description: "Favourites you haven't worn recently.",
    section: 'styleHabits',
    type: 'list',
  },
  {
    id: 'uniformCombo',
    title: 'Your uniform',
    description: 'Most common category combinations you wear.',
    section: 'styleHabits',
    type: 'highlight',
  },
  {
    id: 'valueLeaders',
    title: 'Best value pieces',
    description: 'Clothes delivering superb cost-per-wear.',
    section: 'value',
    type: 'list',
  },
  {
    id: 'valueLaggards',
    title: 'Worst value pieces',
    description: 'Items that need more love to justify their cost.',
    section: 'value',
    type: 'list',
  },
  {
    id: 'sustainabilityScore',
    title: 'Sustainability score',
    description: 'How sustainably you rewear your pieces.',
    section: 'value',
    type: 'score',
  },
  {
    id: 'closetGhosts',
    title: 'Closet ghosts',
    description: "Pieces you've ignored for 6+ months.",
    section: 'value',
    type: 'list',
  },
  {
    id: 'neverWorn',
    title: 'Never worn',
    description: 'Items you added but never wore.',
    section: 'value',
    type: 'list',
  },
  {
    id: 'versatileHero',
    title: 'Most versatile piece',
    description: 'The item appearing in the most outfits.',
    section: 'value',
    type: 'highlight',
  },
  {
    id: 'financialOverview',
    title: 'Financial overview',
    description: 'Average price, total value, and big-ticket items.',
    section: 'financial',
    type: 'cards',
    span: 'lg:col-span-6 xl:col-span-4',
  },
  {
    id: 'spendByCategory',
    title: 'Investment by category',
    description: 'Where your wardrobe budget goes.',
    section: 'financial',
    type: 'chart',
  },
  {
    id: 'spendByBrand',
    title: 'Investment by brand',
    description: 'Brands you invest in most.',
    section: 'financial',
    type: 'chart',
  },
  {
    id: 'seasonalSpend',
    title: 'Seasonal spend',
    description: 'How spending shifts across seasons.',
    section: 'financial',
    type: 'chart',
  },
];

export const MIN_MODULES = 4;
export const MAX_MODULES = 6;
